version: '3'
services:
   router_r1:
       image: alpine
       container_name: router_r1
       privileged: true
       tty: true
       cap_add:
         - NET_ADMIN
         - SYS_MODULE
       sysctls:
         - net.ipv4.ip_forward=1
         - net.ipv4.tcp_timestamps=0
       networks:
            network_1:
              ipv4_address: 192.168.0.2
            network_2:
              ipv4_address: 172.168.1.3
   client_1:
    image: alpine
    container_name: client_1
    privileged: true
    tty: true
    networks:
      network_1:
        ipv4_address: 192.168.0.3
   client_3:
     image: alpine
     container_name: client_3
     privileged: true
     tty: true
     networks:
        network_1:
             ipv4_address: 192.168.0.4
   client_5:
      image: alpine
      container_name: client_5
      privileged: true
      tty: true
      networks:
         network_1:
             ipv4_address: 192.168.0.5
   client_2:
     image: alpine
     container_name: client_2
     privileged: true
     tty: true
     networks:
        network_2:
          ipv4_address: 172.168.1.2
   client_4:
     image: alpine
     container_name: client_4
     privileged: true
     tty: true
     networks:
         network_2:
          ipv4_address: 172.168.1.4
   client_6:
      image: alpine
      container_name: client_6
      privileged: true
      tty: true
      networks:
            network_2:
               ipv4_address: 172.168.1.5
networks:

   network_1:
           driver: bridge
           ipam:
              config:
                 - subnet: 192.168.0.0/24
                   gateway: 192.168.0.1

   network_2:
           driver: bridge
           ipam:
              config:
                - subnet: 172.168.1.0/24
                  gateway: 172.168.1.1


                                         